definitions:
  dto.CreateOpticalDriveRequest:
    properties:
      manufacturer:
        type: string
      powerConsumption:
        type: number
      type:
        type: string
    type: object
  dto.Filter:
    properties:
      filterType:
        type: string
      form:
        type: string
      to:
        type: string
      type:
        type: string
    type: object
  dto.LoginByUsername:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.PaginationInputWithFilter:
    properties:
      filter:
        additionalProperties:
          $ref: '#/definitions/dto.Filter'
        type: object
      page_number:
        type: integer
      page_size:
        type: integer
      sort:
        items:
          $ref: '#/definitions/dto.SortDto'
        type: array
    type: object
  dto.RefreshTokenDTO:
    properties:
      refreshToken:
        type: string
    type: object
  dto.RegisterByUsername:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - firstName
    - password
    - username
    type: object
  dto.SortDto:
    properties:
      colId:
        type: string
      string:
        type: string
    type: object
  dto.TokenDetail:
    properties:
      accessToken:
        type: string
      accessTokenExpireTime:
        type: integer
      refreshToken:
        type: string
      refreshTokenExpireTime:
        type: integer
    type: object
  dto.UpdateOpticalDriveRequest:
    properties:
      manufacturer:
        type: string
      powerConsumption:
        type: number
      type:
        type: string
    type: object
  helper.Response:
    properties:
      err:
        type: string
      result: {}
      statusCode:
        $ref: '#/definitions/helper.ResultCode'
      success:
        type: boolean
    type: object
  helper.ResultCode:
    enum:
    - 0
    - 40001
    - 40002
    - 40101
    - 40301
    - 40401
    - 42901
    - 42902
    - 50001
    - 50002
    type: integer
    x-enum-varnames:
    - Success
    - ValidationError
    - Error
    - AuthError
    - ForbiddenError
    - NotFoundError
    - LimiterError
    - OtpLimiterError
    - CustomRecovery
    - InternalError
info:
  contact: {}
paths:
  /v1/optical-drive/:
    post:
      consumes:
      - application/json
      description: Create a OpticalDrive
      parameters:
      - description: Create a OpticalDrive
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateOpticalDriveRequest'
      responses:
        "201":
          description: OpticalDrive response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - AuthBearer: []
      summary: Create a OpticalDrive
      tags:
      - OpticalDrive
  /v1/optical-drive/{id}:
    delete:
      consumes:
      - application/json
      description: Delete OpticalDrive
      responses:
        "204":
          description: OpticalDrive response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - AuthBearer: []
      summary: Delete OpticalDrive
      tags:
      - OpticalDrive
    get:
      consumes:
      - application/json
      description: GetOpticalDriveById
      responses:
        "200":
          description: GetOpticalDriveById response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - AuthBearer: []
      summary: Get OpticalDrive By Id
      tags:
      - OpticalDrive
    put:
      consumes:
      - application/json
      description: Update OpticalDrive
      parameters:
      - description: ' Update OpticalDrive'
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateOpticalDriveRequest'
      responses:
        "200":
          description: OpticalDrive response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - AuthBearer: []
      summary: Update OpticalDrive
      tags:
      - OpticalDrive
  /v1/optical-drive/all/:
    post:
      consumes:
      - application/json
      description: Get All With Pagination
      parameters:
      - description: Get All With Pagination
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.PaginationInputWithFilter'
      responses:
        "201":
          description: OpticalDrive response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      security:
      - AuthBearer: []
      summary: Get All With Pagination
      tags:
      - OpticalDrive
  /v1/users/login:
    post:
      consumes:
      - application/json
      description: Login users with username and password
      parameters:
      - description: LoginUser
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginByUsername'
      responses:
        "200":
          description: response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: LoginUser
      tags:
      - Users
  /v1/users/logout:
    post:
      consumes:
      - application/json
      description: Get a new logout user and expire JwtToken
      responses:
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
        "418":
          description: AccessToken response
          schema:
            $ref: '#/definitions/helper.Response'
      summary: LogoutUser
      tags:
      - Users
  /v1/users/profile:
    post:
      consumes:
      - application/json
      description: show user details
      responses:
        "200":
          description: UserDetail response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: ShowUserDetail
      tags:
      - Users
  /v1/users/refresh:
    post:
      consumes:
      - application/json
      description: Get a new AccessToken With Refresh token (key rotation is on)
      parameters:
      - description: Get a new AccessToken With Refresh token
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshTokenDTO'
      responses:
        "200":
          description: AccessToken response
          schema:
            allOf:
            - $ref: '#/definitions/helper.Response'
            - properties:
                result:
                  $ref: '#/definitions/dto.TokenDetail'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: RefreshToken
      tags:
      - Users
  /v1/users/register:
    post:
      consumes:
      - application/json
      description: register users with username and password
      parameters:
      - description: RegisterByUsername
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterByUsername'
      responses:
        "201":
          description: response
          schema:
            $ref: '#/definitions/helper.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/helper.Response'
      summary: RegisterUser
      tags:
      - Users
swagger: "2.0"
